---

# maintenance / fastd-query
- name: Creates file etc/{{ gateways[unit_id].site }}
  copy:
    content: "MAINTENANCE=0\n" 
    dest: "/etc/{{ gateways[unit_id].site }}"
    mode: 0644

- name: Create excutable file (maintenance)
  template: 
    src: maintenance.j2
    dest: /usr/local/bin/maintenance
    mode: '0755'

- name: Create excutable file (fastd-query)
  copy:
    src: fastd-query
    dest: /usr/local/bin/fastd-query
    mode: '0755'
