---

- name: Install nginx und certbot
  apt:
    name:        ['nginx', 'python-simplejson', 'certbot', 'python3-certbot-nginx']

- name: Generate dhparams
  shell:         openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates:     /etc/nginx/dhparams.pem

- name: create letsencrypt directory
  file: 
    name:        /var/lib/letsencrypt
    state:       directory
    owner:       www-data
    group:       www-data
    mode:        g+s

- name: create .acme-challenge directory
  file: 
    name:        /var/lib/letsencrypt/.well-known/acme-challenge
    state:       directory
    owner:       www-data
    group:       www-data

- name: Remove default nginx config
  file: 
    name:        /etc/nginx/sites-enabled/default 
    state:       absent

- name: Install system nginx config
  copy:
    src:         nginx.conf
    dest:        /etc/nginx/nginx.conf

- name: Create snippet letsencrypt.conf
  template:
    src:         templates/letsencrypt.conf.j2
    dest:        /etc/nginx/snippets/letsencrypt.conf

- name: Create snippet ssl.conf
  template:
    src:         templates/ssl.conf.j2
    dest:        /etc/nginx/snippets/ssl.conf

- name: Create snippet cors.conf
  template:
    src:         templates/cors.conf.j2
    dest:        /etc/nginx/snippets/cors.conf

# test, whether certificate already exist
- name: Check certs exist
  stat:          path=/etc/letsencrypt/live/{{ unit_name }}/fullchain.pem
  register:      st

- name: Install nginx site for specified site
  template:
    src:         templates/default_nokey.j2
    dest:        /etc/nginx/sites-enabled/default
  when:          not st.stat.exists

- name: Reload nginx to activate letsencrypt site
  command:       systemctl restart nginx
  when:          not st.stat.exists

- name: Create letsencrypt certificate
  shell:         certbot certonly --agree-tos --email {{ letsencrypt_email }} --webroot -w /var/lib/letsencrypt/ -d {{ unit_name }}
  when:          not st.stat.exists

- name: Install nginx site for specified site
  template:
    src:         templates/default_std.j2
    dest:        /etc/nginx/sites-enabled/default

- name: Reload nginx to activate letsencrypt site
  command:       "systemctl restart nginx"

# Auto-renew certificates and reload nginx
- name: Add crontab to renew certificates
  cron: 
    minute:      "30" 
    hour:        "3" 
    weekday:     "1"
    job:         "certbot renew >> /var/log/le-renew.log"

- name: Add crontab to reload server
  cron: 
    minute:      "35"
    hour:        "3" 
    weekday:     "1" 
    job:         "systemctl restart nginx"



