---

# ip -forwarding

- name: IP4-forwarding
  lineinfile:
    dest:                 /etc/sysctl.conf
    regexp:               "net.ipv4.ip_forward"
    line:                 "net.ipv4.ip_forward=1"
    state:                present

- name: IP6-forwarding
  lineinfile:
    dest:                 /etc/sysctl.conf
    regexp:               "net.ipv6.conf.all.forwarding"
    line:                 "net.ipv6.conf.all.forwarding=1"
    state:                present

# load executable for ip mesh config

- name: create executable for ip mesh config
  template: 
     src:                 iptables_xxxx.sh.j2 
     dest:                /etc/fastd/iptables_{% for idm in gateways[unit_id].domains | dict2items %}{% if loop.first %}{{hoods[idm.key].site}}{% endif %}{% endfor %}.sh
     mode:                '0755'

# iptables

- name: Define base-rules
  template: 
    src:                  iptables.up.rules.j2 
    dest:                 /etc/iptables.up.rules

- name: Create excutable file to reload iptables - base rules
  copy: 
     src:                 iptables 
     dest:                /etc/network/if-pre-up.d/iptables
     mode:                '0755'

# mesh-interfaces

- name: Configure mesh interfaces
  template: 
    src:                  mesh.conf.j2 
    dest:                 /etc/network/interfaces.d/mesh.conf
  notify: 
  - Run ip mesh config
  - Reload systemd
  - Restart network
  - Reload iptables
  register:               task_result



