---

# ip -forwarding

- name: IP4-forwarding
  lineinfile:
    dest:                 /etc/sysctl.conf
    regexp:               "net.ipv4.ip_forward"
    line:                 "net.ipv4.ip_forward=1"
    state:                present

- name: IP6-forwarding
  lineinfile:
    dest:                 /etc/sysctl.conf
    regexp:               "net.ipv6.conf.all.forwarding"
    line:                 "net.ipv6.conf.all.forwarding=1"
    state:                present

# iptables

- name: Define base-rules
  template: 
    src:                  iptables.up.rules.j2 
    dest:                 /etc/iptables.up.rules

- name: Create excutable file to reload iptables - base rules
  copy: 
     src:                 iptables 
     dest:                /etc/network/if-pre-up.d/iptables
     mode:                '0755'

# mesh-interfaces

- name: Configure mesh interfaces gateway
  template: 
    src:                  mesh.conf.j2 
    dest:                 /etc/network/interfaces.d/mesh.conf
  notify: 
  - Reload systemd
  - Restart network
  - Run ip mesh config gw
  register:               task_result
  when:                   unit_type == "gateway"

- name: Configure mesh interfaces collector
  template: 
    src:                  mesh.conf.j2 
    dest:                 /etc/network/interfaces.d/mesh.conf
  notify: 
  - Reload systemd
  - Restart network
  - Run ip mesh config coll
  register:               task_result
  when:                   unit_type == "collector"



