- name: Hostname im Prompt setzen
  hostname: 
    name:           "{{ unit_idn }}"

- name: Hostname in /etc/hostname setzen
  copy:
    content:        "{{ unit_idn }}}{{'\n'}}"
    dest:           /etc/hostname
    owner:          root
    group:          root
    mode:           0644

- name: Hostname für IPv4 in /etc/hosts setzen
  lineinfile:
    dest:           /etc/hosts
    regexp:         "^127.0.1.1"
    line:           "127.0.1.1{{'\t'}}{{ unit_idn }}{{'\t'}}{{ unit_id }}.gw.{{ sites[gateways[unit_id].site].domain }}"
    state:          present

- name: Hostname für IPv4 in /etc/hosts setzen
  lineinfile:
    dest:           /etc/hosts
    regexp:         "^{{ gateways[unit_id].ipv4 }}"
    insertafter:    "^127.0.1.1"
    line:           "{{ gateways[unit_id].ipv4 }}{{'\t'}}{{ unit_id }}.gw.{{ sites[gateways[unit_id].site].domain }}{{'\t'}}{{ unit_idn }}"
    state:          present

- name: Hostname für IPv6 in /etc/hosts setzen
  lineinfile:
    dest:           /etc/hosts
    regexp:         "^::1"
    line:           "::1{{'\t'}}{{unit_idn}}{{'\t'}}{{ unit_id }}.gw.{{ sites[gateways[unit_id].site].domain }}{{'\t'}}localhost ip6-localhost ip6-loopback"
    state:          present

- name: Adresse (IPv4) setzen
  lineinfile:
    dest:           /etc/hosts
    regexp:         "^{{ gateways[unit_id].domains[igw.key].bat_ipv4 | ipaddr('address')}}"
    insertafter:    "^127.0.1.1"
    line:           "{{ gateways[unit_id].domains[igw.key].bat_ipv4 | ipaddr('address')}}{{'\t'}}{{ hoods[igw.key].sname }}"
    state:          present
  loop:             "{{ gateways[unit_id]['domains'] | dict2items }}"
  loop_control:
    loop_var:       igw
  when:             unit_type == "gateway"

- name: Adresse2 (IPv6) setzen
  lineinfile:
    dest:           /etc/hosts
    regexp:         "^{{ gateways[unit_id].domains[igw.key].bat_ipv6 | ipaddr('address')}}"
    line:           "{{ gateways[unit_id].domains[igw.key].bat_ipv6 | ipaddr('address')}}{{'\t'}}{{ hoods[igw.key].sname }}"
    state:          present
  loop:             "{{ gateways[unit_id]['domains'] | dict2items }}"
  loop_control:
    loop_var:       igw
  when:             unit_type == "gateway"

