---

- name: Setup common roles on all hosts
  hosts: all
  roles:
  - hostname
  - common

- name: Setup collector
  hosts: all
  roles:
  - ntp
  - batman
  - fastd
  - meshconfig
  - reboot-unit
  - bind
#  - yanic
#  - nginx

