---

- name: Setup common roles on all hosts
  hosts: all
  roles:
  - hostname
  - common

- name: Setup collector step 1
  hosts: all
  roles:
  - ntp
  - batman
  - fastd
  - meshconfig
  - reboot-unit

- name: Setup collector step 1
  hosts: all
  roles:
  - bind

