---

- name: Setup common roles on all hosts
  hosts: 11.gw.freifunk-nordheide.de, 13.gw.freifunk-nordheide.de 
  roles:
  - hostname
  - ntp
  - common

- name: Setup gateways
  hosts: 11.gw.freifunk-nordheide.de, 13.gw.freifunk-nordheide.de
  roles:
  - batman
  - fastd
  - ipf-iptables-interfaces
  - radvd
  - dhcp
  - bind
  - respondd
  - nginx
  - yanic

- name: Reboot gateways
  hosts: 11.gw.freifunk-nordheide.de, 13.gw.freifunk-nordheide.de
  roles:
  - reboot-unit
