---

- name: Setup common roles on all hosts
  hosts: all
  roles:
  - hostname
  - common

- name: Setup gateways
  hosts: all
  roles:
  - ntp
  - batman
  - fastd
  - meshconfig
  - radvd
  - bind
  - respondd
  - maintenance
  - nginx
  - dhcp

- name: Setup yanic
  hosts: all
  roles:
  - yanic
 
