---

- name:        Sync Push task - Executed on source host "statistik.freifunk-nordheide.de"
  hosts:                "stat02.freifunk-nordheide.de" 
  user:                 freifunker
  tasks:
    - name:    Copy the complete db from statistik to stat01 using Method Push
      tags:             sync-push
      synchronize:
        src:            "/var/lib/grafana/grafana.db"
        dest:           "/var/lib/grafana/grafana.db"
        mode:           push
        recursive:      false
#        rsync_path:     "sudo rsync" 
      become:           true
      delegate_to:      "statistik.freifunk-nordheide.de"

