---

- name: Setup common roles on all hosts
  hosts: all
  roles:
  - hostname
  - common

#- name: Setup statserver
#  hosts: all
#  roles:
#  - ntp
#  - bind
#  - nginx
# # - yanic

#- name: Reboot gateways
#  hosts: all
#  roles:
#  - reboot-unit

