---

- name: Install dhcp server
  apt: name=isc-dhcp-server

- name: Configure dhcp server
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf
  notify: Restart isc-dhcp-server

- name: Specify dhcp interfaces
  lineinfile:
    dest: /etc/default/isc-dhcp-server
    line: "INTERFACESv4=\"{{ dhcpd_interfaces }}\""
    regexp: "^INTERFACESv4="
  notify: Restart isc-dhcp-server

- name: Start the dhcp server
  service: name=isc-dhcp-server state=started enabled=yes
