---

# Install meshviewer

- name: Install curl
  apt:
    name:
    - curl

- name: Get nodejs
  shell: "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -"

- name: Install node_js
  apt:
    name: nodejs

- name: Remove "cmdtest" package # to remove wrong yarn
  apt:
    name: cmdtest
    state: absent

- name: Remove "yarn" package # to remove wrong yarn
  apt:
    name: yarn
    state: absent

- name: Get yarn
  shell: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"

- name: Prepare yarn
  shell: 'echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list'

- name: Install yarn
  apt:
    name: yarn
    update_cache: yes

- name: Create directories
  file: path={{ item }}/ state=directory owner=www-data
  with_items:
  - /var/www
  - /var/www/html
  - /var/www/html/meshviewer

- name: Get meshviewer 
  git: 
    repo: "https://github.com/ffsh/meshviewer.git"
    dest: "/var/www/html/meshviewer"

- name: Run yarn after changing directory
  shell: "yarn"
  args:
    chdir: "/var/www/html/meshviewer"

- name: Configure meshviewer1
  template: 
    src: config.js.j2
    dest: /var/www/html/meshviewer/config.js

- name: Configure meshviewer2
  template: 
    src: index.html.j2
    dest: /var/www/html/meshviewer/html/index.html

- name: Compile meshviewer
  shell: "yarn run gulp"
  args:
    chdir: /var/www/html/meshviewer



