---
- name: parameter
  set_fact:
    towner:             marcus
    tgroup:             marcus
    sitedir:            "{{ playbook_dir }}/firmware_site/"
    gluon_version:      "v2018.2"
    gluon_dir:		"/home/marcus/ff_firmware/v2018.2/"

- name: Install misc software local
  apt: 
    name:
    - git 
    - subversion
    - python
    - build-essential
    - gawk
    - unzip
    - libncurses-dev
    - libz-dev
    - libssl-dev
    - wget
    - time

- name: Clone gluon
  git: 
    repo:          "https://github.com/freifunk-gluon/gluon.git" 
    dest:          "{{gluon_dir}}gluon/" 
    version:       "{{ gluon_version }}"

- name: Create local dir
  file:                 
    path:               "{{ gluon_dir }}gluon/site/" 
    state:              directory
    mode:               755
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"

- name: Copy site data
  copy:
    src:                "{{ sitedir }}"
    dest:               "{{ gluon_dir }}gluon/site/"
    directory_mode:     "true"
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"




#- name: Build the default target
#  make:
#    chdir: "{{gluon_dir}}/gluon/"

...
