---
- name: Include fastd_keys
  include_vars:
    file:      "{{ playbook_dir }}/../ansible-keys/fastd_keys.yml"

- name: parameter
  set_fact:
    towner:             marcus
    tgroup:             marcus
    sitedir:            "{{ playbook_dir }}/../ffnh_t1"
    targetsite:         ffnh
    targetdomains:
    - "00"   # Alte Umgebung
#    - "01"   # Standardhood
    - "06"   # l2tp
#    - "10"   # ffnh Veranstaltungen (intern)
    - "11"   # ffnh
    - "12"   # ffnh
    - "13"   # ffnh
    - "14"   # ffnh
#    - "15"   # ffnh Stade
    - "21"   # ffcux
    - "22"   # ffcux
    - "23"   # ffcux
    targetdefault:      "01"

- name: Create local dir
  file:                 
    path:               "{{ item }}" 
    state:              directory
    mode:               '1755'
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"
  with_items:
  - "{{ sitedir }}/domains/"
  - "{{ sitedir }}/i18n/"
      
- name: Create modules
  template:
    src:                modules.j2
    dest:               "{{ sitedir }}/modules"
    mode:               '644'
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"

- name: Create site.mk
  template:
    src:                site.mk.j2
    dest:               "{{ sitedir }}/site.mk"
    mode:               '644'
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"

- name: Create site.conf
  template:
    src:                site.conf.j2
    dest:               "{{ sitedir }}/site.conf"
    mode:               '644'
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"

- name: Create domain.conf
  template:
    src:                domain.conf.j2
    dest:               "{{ sitedir }}/domains/{{ hoods[item].sname }}.conf"
    mode:               '644'
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"
  loop:                 "{{ targetdomains }}"                 

- name: Copy i18n
  copy:
    src:                ../templates/i18n/
    dest:               "{{ sitedir }}/domains/i18n/"
    recurse:            "true"
    mode:               '755'
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"

...
