---
- name: parameter
  set_fact:
    towner:             freifunker
    tgroup:             freifunker
    sitedir:            "{{ playbook_dir }}/firmware_site/"
    gluon_version:      "v2021.1.1"
    gluon_dir:		"/home/freifunker/newenv/firmware/v2021.1.1.1/"

- name: Install misc software local
  apt: 
    name:
    - git 
    - subversion
    - python
    - build-essential
    - gawk
    - unzip
    - libncurses-dev
    - libz-dev
    - libssl-dev
    - wget
    - time

- name: Clone gluon
  git: 
    repo:          "https://github.com/freifunk-gluon/gluon.git" 
    dest:          "{{gluon_dir}}gluon/" 
    version:       "{{ gluon_version }}"

- name: Create dir
  file:                 
    path:               "{{ gluon_dir }}gluon/site/" 
    state:              directory
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"

- name: Copy site data
  copy:
    src:                "{{ sitedir }}"
    dest:               "{{ gluon_dir }}gluon/site/"
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"


...
