---
      
- name:         Restart respondd
  service:  
    name:       "respondd@{{ hoods[item.key].sname }}" 
    state:      restarted
  loop:         "{{ gateways[unit_id]['domains'] | dict2items }}"

- name:         Reload systemd
  command:      systemctl daemon-reload
