---
- name: parameter
  set_fact:
    towner:             freifunker
    tgroup:             freifunker
    sitedir:            "{{ playbook_dir }}/firmware_site/"
    gluon_dir:		"/home/freifunker/newenv/firmware/v2020.2.2.1/"

- name: make update
  make:
    chdir:              "{{ gluon_dir }}gluon"
    target:             "update"
  become:               false

- name: make ar71xx-generic
  make: 
    chdir:              "{{ gluon_dir }}gluon"
    params:		
      jobs:             2
    target:             "GLUON_TARGET=ar71xx-generic"
  become:               false

#- name: make ar71xx-tiny
#  make: 
#    chdir:              "{{ gluon_dir }}gluon"
#    params:		
#      jobs:             8
#    target:             "GLUON_TARGET=ar71xx-tiny"

#- name: make ar71xx-nand
#  make: 
#    chdir:              "{{ gluon_dir }}gluon"
#    params:		
#      jobs:             8
#    target:             "GLUON_TARGET=ar71xx-nand"

#- name: make ipq40xx-generic
#  make: 
#    chdir:              "{{ gluon_dir }}gluon"
#    params:		
#      jobs:             8
#    target:             "GLUON_TARGET=ipq40xx-generic"
#  
#- name: make listet targets
#  make: 
#    chdir:              "{{ gluon_dir }}gluon"
#    params:		
#      jobs:             8
#    target:             "GLUON_TARGET={{ item }}"
#  with_items:
##    - "ar71xx-generic"
##   - "ar71xx-tiny"
##   - "ar71xx-nand"
#    - "ath79-generic"    # e.g. devolos
##    - "brcm2708-bcm2708" # raspberry pi1 
##    - "brcm2708-bcm2709" # raspberry pi2
##   - "ipq40xx-generic"  # e.g. avm 4040
#    - "ipq806x-generic"  # netgear R7800
#    - "lantiq-xrx200"
#    - "lantiq-xway"
##    - "mpc85xx-generic"
##    - "mpc85xx-p1020"
##    - "ramips-mt7621"
##    - "ramips-mt7620"
##    - "ramips-mt76x8"
##    - "ramips-rt305x"
##    - "sunxi-cortexa7"
#    - "x86-generic"
#    - "x86-geode"
#    - "x86-legacy"
#    - "x86-64"

...
