---
- name: Include fastd_keys
  include_vars:
    file:      "{{ playbook_dir }}/../ansible-keys/fastd_keys.yml"

- name: parameter
  set_fact:
    towner:             marcus
    tgroup:             marcus
    sitedir:            "{{ playbook_dir }}/firmware_site"
    targetsite:         ffnh
    targetdomains:
    - "00"   # Alte Umgebung
    - "01"   # Standardhood
    - "06"   # l2tp
    - "10"   # ffnh Veranstaltungen (intern)
    - "11"   # ffnh NW
    - "12"   # ffnh NO
    - "13"   # ffnh SO
    - "14"   # ffnh SW
    - "21"   # ffcux Stadt
    - "22"   # ffcux Nord
    - "23"   # ffcux Süd
    - "31"   # ffnh Stade
    - "41"   # ffnh Diverse
    targetdefault:      "00"

- name: Create target dir
  file:                 
    path:               "{{ item }}" 
    state:              directory
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"
  with_items:
  - "{{ sitedir }}/domains/"
  - "{{ sitedir }}/i18n/"
      
- name: Create modules
  template:
    src:                modules.j2
    dest:               "{{ sitedir }}/modules"
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"

- name: Create site.mk
  template:
    src:                site.mk.j2
    dest:               "{{ sitedir }}/site.mk"
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"

- name: Create site.conf
  template:
    src:                site.conf.j2
    dest:               "{{ sitedir }}/site.conf"
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"

- name: Create domain.conf
  template:
    src:                domain.conf.j2
    dest:               "{{ sitedir }}/domains/{{ hoods[item].sname }}.conf"
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"
  loop:                 "{{ targetdomains }}"                 

- name: Copy i18n
  copy:
    src:                "../templates/i18n/{{ item }}"
    dest:               "{{ sitedir }}/i18n/{{ item }}"
    owner:              "{{ towner }}"
    group:              "{{ tgroup }}"
  with_items:
  - "en.po"
  - "de.po"
...
