---

# TEst configure meshviewer
#- name: Create geojson directory
#  file: 
#    path:      "/var/www/html/meshviewer/data/geodata/"
#    state:     directory 
#    owner:     www-data
#    group:     www-data

#- name: Copy geojson files for hoods
#  copy:
#    src:       ../templates/borders/hoods
#    dest:      /var/www/html/meshviewer/data/geodata
#    owner:     www-data
#    group:     www-data

- name: Modify json
  modify_json_areaparms:
    datadir:   "/var/www/html/meshviewer/data/geodata/hoods/"
    sites:     "{{ sites }}"
    hoods:     "{{ hoods }}"
  register: result

#- debug:
#    msg: "{{  result.result | to_nice_json(indent=2) }}"




