---

# Configure meshviewer
- name: Schalter für Copy der Geo-Daten
  set_fact: 
    update_geo: false
    meshv_dir: "/var/www/html/meshviewer"

- name: Config directories for meshviewer data
  file: 
    path:      "{{ meshv_dir }}/data/{{ igw.value.id }}/offline/"
    state:     directory 
    owner:     www-data
    group:     www-data
  loop:        "{{ gateways[unit_id].areas|dict2items  }}"
  loop_control:
    loop_var:  igw

- name: Build offline meshviewer.json for each area
  template: 
    src:       "offline_meshviewer.json.j2"
    dest:      "{{ meshv_dir }}/data/{{ igw.value.id }}/offline/meshviewer.json"
    owner:     www-data
    group:     www-data
  loop:        "{{ gateways[unit_id].areas|dict2items  }}"
  loop_control:
    loop_var:  igw

- name: Create geojson directory
  file: 
    path:      "{{ meshv_dir }}/data/geodata/"
    state:     directory 
    owner:     www-data
    group:     www-data
  when:        update_geo == True

- name: Copy geojson data
  template: 
    src:       area_features.json.j2
    dest:      "{{ meshv_dir }}/data/geodata/areafeatures.json"
    owner:     www-data
    group:     www-data
  when:        update_geo == True

- name: Copy geojson files for hoods
  copy:
    src:       ../templates/borders/hoods
    dest:      "{{ meshv_dir }}/data/geodata"
    owner:     www-data
    group:     www-data
  when:        update_geo == True

- name: Modify json
  modify_json_areaparms:
    datadir:   "{{ meshv_dir }}/data/geodata/hoods/"
    sites:     "{{ sites }}"
    hoods:     "{{ hoods }}"
  when:        update_geo == True
  
- name: Create wget data script
  template: 
    src:       get_nodevalues.j2
    dest:      /usr/local/bin/get_nodevalues
    mode:      "755"

- name: Ensure updating data each minutes
  cron:
    name:      "get data"
    minute:    "*"
    job:       "/usr/local/bin/get_nodevalues"

- name: Create combine meshviewer.json - python script
  template: 
    src:       combine_meshv_json.j2
    dest:      /usr/local/bin/combine_meshv_json
    mode:      "755"

- name: Ensure creating meshviewer.json each minute; delay 10 sec"
  cron:
    name:      "combine meshviewer"
    minute:    "*"
    job:       "sleep 10; /usr/bin/python3 /usr/local/bin/combine_meshv_json"

- name: Configure meshviewer1 - config.js
  template: 
    src:       config.js.j2
    dest:      "{{ meshv_dir }}/config.js"

- name: Configure meshviewer2 - index.html
  template: 
    src:       index.html.j2
    dest:      "{{ meshv_dir }}/html/index.html"

- name: Compile meshviewer
  shell:       "yarn run gulp"
  args:
    chdir:     "{{ meshv_dir }}"



