---

- name: copy bashrc
  copy:  
    src: bashrc 
    dest: /root/.bashrc
    force: yes

- name: first try apt update
  command: apt update

- name: Install misc software
  apt: 
    name:
    - build-essential
    - git
    - apt-transport-https
    - net-tools
    - mc
    - sudo
    - dnsutils
    - bridge-utils
    - iptables-persistent
    - fail2ban
    - socat
    - jq
  register: task_result

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: task_result is changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: task_result is changed
