---

- name: install bind9
  apt:
    pkg: bind9
    state: present

- name: Load bind options
  template: 
    src: named.conf.options.j2 
    dest: /etc/bind/named.conf.options

- name: Load bind options
  template: 
    src: named.conf.local.j2 
    dest: /etc/bind/named.conf.local
    force: yes

- name: Creates directory zones
  file:
    path: /etc/bind/zones
    state: directory

- name: Creates directory zone
  file:
    path: /etc/bind/zones/{{ site_code }}
    state: directory

- name: Load zone.conf
  template: 
    src: zone.conf.j2 
    dest: /etc/bind/zones/{{ site_code }}/{{ site_code }}.conf
 
- name: Load db.zone
  template: 
    src: db.{{ site_code }}.j2 
    dest: /etc/bind/zones/{{ site_code }}/db.{{ site_code }}
  notify: reload daemon
  notify: restart bind9

