---
#
# file: grafana/tasks/main.yml
#
- name: Grafana Version
  set_fact: 
    grafana_version:               "8.1.1"
    # Install first the above version because the existing grafana.db used here (containing all our charts) is based on this version
    # Update grafana to a newer version after the first installation directly on the VM - this will guarantee a consistent db

- name: ensure apt dependencies are installed
  apt:
    name:                          ["apt-transport-https"]
    state:                         present
  become:                          yes

- name: ensure grafana apt key is present
  apt_key:
    url:                           "https://packages.grafana.com/gpg.key"
    state:                         present
    validate_certs:                false
  become:                          yes
  register:                        _add_apt_key
  retries:                         5
  delay:                           2

- name: ensure grafana apt repository is present
  apt_repository:
    repo:                          "deb https://packages.grafana.com/oss/deb stable main"
    update_cache:                  yes
    state:                         present
  become:                          yes
  register:                        _update_apt_cache
  until:                           _update_apt_cache is succeeded
  retries:                         5
  delay:                           2

- name: ensure grafana is installed
  package:
    name:                          "grafana{{ (grafana_version != 'latest') | ternary('=' ~ grafana_version, '') }}"
    state:                         "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  become:                          yes
  register:                        _install_packages
  until:                           _install_packages is succeeded
  retries:                         5
  delay:                           2
  notify:                          restart grafana

- name: Ensure integrity of grafana configuration.
  template:
    src:                           "grafana.ini.j2"
    dest:                          "/etc/grafana/grafana.ini"
    owner:                         grafana
    group:                         grafana
    mode:                          0644
  become:                          yes
  notify:                          restart grafana

#- name: Ensure integrity of grafana configuration.
#  template:
#    src: 'grafana-server.j2'
#    dest: '/etc/default/grafana-server'
#    owner: "{{ grafana_user }}"
#    group: "{{ grafana_group }}"
#    mode: 0644
#  become: yes
#  notify: restart grafana
#  tags: configuration

#- name: ensure grafana pid directory is present
#  file:
#    path="{{ grafana_pid_file_dir }}"
#    owner="{{ grafana_user }}"
#    group="{{ grafana_group }}"
#    mode=0755
#    state=directory
#  become: yes
    
- name: ensure grafana directories ownership and permissions
  file:
    path:                          "{{ item }}"
    owner:                         grafana
    group:                         grafana
    mode:                          0755
    state:                         directory
  become:                          yes
  with_items:
    - /etc/grafana
    - /var/lib/grafana
    - /usr/share/grafana
    - /var/log/grafana
    - /var/lib/grafana/plugins
    - /var/run/grafana

- name: Copy existing grafana.db
  copy:        
    src:                           grafana.db 
    dest:                          /var/lib/grafana/grafana.db 
    owner:                         grafana
    group:                         grafana
    mode:                          0755 
    force:                         yes
  become:                          yes  

- name: ensure grafana is running and enabled to start on boot
  service:
    name:                          grafana-server
    state:                         started
    enabled:                       yes
  become:                          yes

